### ISSUE TITLE
KeepassXC return error 15 (No logins found) for all URLs

### ISSUE THREAD

**Issue by aearil** [ususdei/qute-keepassxc#1]
qute-keepassxc seems to be correctly associated with keepassxc (test_association succeeds), but every URLs I try, even exact matches to some keepassxc entries, result in `KeepassXC Error [15]: No logins found`

I've also tested the script in standalone mode so I can confirm that the correct URL is sent, at least right up until the message is encrypted.

Any ideas ? Could it have anything to do with the "Enable integration for these browsers" settings in keepassxc ? (I enabled them all, didn't change anything).

Also, the same database and keepassxc install works flawlessly with firefox. (I'm running keepassxc 2.5.3-1)

**Comment by toerd** [comment]
@aearil Had the same issue. After some troubleshooting I found a possible workaround/solution for the problem (Has to be confirmed by original author since I am not sure if I/we did something fundamentally wrong).

### For solution see #2 

My KeepassXC version is: **2.5.3**

My keepassxc-browser config looks as follows:
![2020-04-04_19-59-57](https://user-images.githubusercontent.com/15987853/78458074-0f85c200-76af-11ea-83fc-193a57acb121.png)
![2020-04-04_20-00-11](https://user-images.githubusercontent.com/15987853/78458076-157ba300-76af-11ea-9de0-2d5eb94e37dc.png)

My qutebrowser config line for the userscript call looks like this:
`
config.bind(leader+'p', 'spawn --userscript ~/.config/qutebrowser/scripts/qute-keepassxc --key $INSERT_YOUR_GPG_ENCRYPT_KEY_ID_HERE')
`

To find the GPG ID: `gpg --card-status` (if on card) else `gpg -k` -> search for smth that identifies your key unambiguous e.g. long number -> `gpg --edit-key $THAT_NUMBER` -> look for the ID (e.g. rsa4096/ID_IS_HERE)

Hope that helps someone with the same problem.

Thanks @ususdei for creating this script!
